// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjW5IplxJF3HlcgBD6VtTicwpt8sS5MMY',
    appId: '1:240229471911:android:7d304f115727a3f992ed82',
    messagingSenderId: '240229471911',
    projectId: 'challenge-88',
    databaseURL: 'https://challenge-88-default-rtdb.firebaseio.com',
    storageBucket: 'challenge-88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCigdTs7DHkIyT_REUU_MV-4yh8-bm8Xxc',
    appId: '1:240229471911:ios:73c1441feb40927f92ed82',
    messagingSenderId: '240229471911',
    projectId: 'challenge-88',
    databaseURL: 'https://challenge-88-default-rtdb.firebaseio.com',
    storageBucket: 'challenge-88.appspot.com',
    iosClientId: '240229471911-9m4sfsef1or4nilk05msgrjr2ctql5sm.apps.googleusercontent.com',
    iosBundleId: 'com.wiz.onlinechallange.globalOnline',
  );
}
